#Include the drone settings

IMAGE_INSTALL += "lib32-lib-robotics-camera"
IMAGE_INSTALL += "initscripts-functions"
IMAGE_INSTALL += "openssl"
IMAGE_INSTALL += "lib32-openssl"
IMAGE_INSTALL += "lib32-ncurses"
IMAGE_INSTALL += "lib32-ncurses-terminfo"
IMAGE_INSTALL += "lib32-ncurses-terminfo-base"
IMAGE_INSTALL += "lib32-ncurses-libncurses"
IMAGE_INSTALL += "lib32-libgomp"
IMAGE_INSTALL += "lib32-libgomp-dev"
