#!/bin/sh

# Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of The Linux Foundation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ $# -gt 0 ]; then
   resp=$1
fi

while true; do
   if [ -z $resp ]; then
      echo "Do you wish to clear all files under /data?"
      read -p "Answering 'y' will send the device in reboot cycle. [y/n]:" resp
   fi

   case $resp in
      [Yy] )
         target=$(cat /target)
         if [ -f /etc/$target.usrfs.tar.gz ]; then
            mkdir -p /var/volatile/usrfs-defaults/
            tar -xf /etc/$target.usrfs.tar.gz -C /var/volatile/usrfs-defaults/
            if [ $? -eq 0 ]; then
               echo 1 > /var/volatile/userfs-reset-cookie
               reboot
            else
               echo "Extraction of /etc/$target.usrfs.tar.gz usrfs archive failed, /data/ reset not initiated."
               exit
            fi
         else
            echo "Default usrfs file /etc/$target.usrfs.tar.gz not found, /data/ reset not initiated."
            exit
         fi
         break;;
      [Nn] ) exit;;
      * ) echo "Please answer Y or N.";;
   esac
done
