#! /bin/sh
#
# Copyright (c) 2017-2018, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# EMAC Driver init.d script to load EMAC driver

export MODULE_BASE=/lib/modules/`uname -r`/
export PHYID_FILE=/sys/devices/platform/20000.qcom,emac/mdio_bus/dwc_phy-1/dwc_phy-1:00/phy_id
#set -e

case "$1" in
  start)
        echo -n "Starting/Loading Ethernet Driver: "
        echo "eMAC:start/load" > /dev/kmsg
        insmod $MODULE_BASE/extra/emac_dwc_eqos.ko
	if [ -e "$PHYID_FILE" ]; then
		exist=`grep 0x004dd036 $PHYID_FILE 2> /dev/null`
		if [ "$exist" != "" ]; then
			insmod $MODULE_BASE/kernel/drivers/qca-ssdk-nohnat/qca-ssdk.ko
		fi
	fi
        ifconfig eth0 up
        echo "done loading ethernet driver"
        ;;
  stop)
        echo -n "Unloading Ethernet Driver "
        if [ -e "$PHYID_FILE" ]; then
                exist=`grep 0x004dd036 $PHYID_FILE 2> /dev/null`
                if [ "$exist" != "" ]; then
                        rmmod qca_ssdk
                fi
        fi
        rmmod emac_dwc_eqos
        echo "done unloading ethernet driver"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
