#! /bin/sh
#
# Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Create rule in ebtables to receive AVTP (802.1Q type) packets only on eth0 interface.
# This will cause all 802.1Q packets to be received on eth0 and not on bridge0.

set -e

case "$1" in
  start)
        echo -n "Creating ebtables rule for 802.1Q packets: "
        if [ -e /sys/class/net/bridge0/bridge ]; then
          ebtables -t broute -A BROUTING -i eth0 -p 802_1Q -j DROP
        fi
        echo "Done creating routing rule"
        echo "802.1Q packets will be received on eth0"
        ;;
  stop)
        echo -n "Removing ebtables rule for 802.1Q packets: "
        if [ -e /sys/class/net/bridge0/bridge ]; then
          ebtables -t broute -D BROUTING -i eth0 -p 802_1Q -j DROP
        fi
        echo "Done removing routing rule"
        echo "802.1Q packets will be received on bridge0"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
