/sbin/mount-copybind /systemrw/adb_devid  /etc/adb_devid
/sbin/mount-copybind /systemrw/build.prop /etc/build.prop
/sbin/mount-copybind /systemrw/data /etc/data/
/sbin/mount-copybind /systemrw/data/usb /etc/data/usb/
/sbin/mount-copybind /systemrw/data/adpl /etc/data/adpl/
/sbin/mount-copybind /systemrw/data/miniupnpd /etc/data/miniupnpd/
/sbin/mount-copybind /systemrw/data/ipa /etc/data/ipa/
/sbin/mount-copybind /systemrw/rt_tables /etc/data/iproute2/rt_tables
/sbin/mount-copybind /systemrw/boot_hsusb_comp /etc/usb/boot_hsusb_comp
/sbin/mount-copybind /systemrw/boot_hsic_comp /etc/usb/boot_hsic_comp
/sbin/mount-copybind /systemrw/misc/wifi /etc/misc/wifi
/sbin/mount-copybind /systemrw/bluetooth /etc/bluetooth
