umount /etc/adb_devid
umount /etc/build.prop
umount /etc/data/*
umount /etc/data/usb/*
umount /etc/data/miniupnpd/*
umount /etc/data/ipa/*
umount /etc/data/adpl/*
umount /etc/data/iproute2/rt_tables
umount /etc/usb/boot_hsusb_comp
umount /etc/usb/boot_hsic_comp
umount /etc/bluetooth/*
