#!/bin/bash

QTIPATH=/usr/qtiroot

if [[ ! -f /run/qtiMounted ]]; then
	touch /run/qtiMounted
	mount --rbind /dev ${QTIPATH}/dev
	mount --rbind /data ${QTIPATH}/data
	mount --rbind /sys ${QTIPATH}/sys
	mount --rbind /proc ${QTIPATH}/proc
	mount --bind ${QTIPATH}/tmp
	mount --rbind /var ${QTIPATH}/var
	mount --rbind /run ${QTIPATH}/run
	mount --rbind /firmware ${QTIPATH}/firmware
	# init camera (ankiinit)
	CAM_REG_GPIO=83
	if [ ! -d /sys/class/gpio/gpio$CAM_REG_GPIO ]; then
		echo $CAM_REG_GPIO > /sys/class/gpio/export
	fi
	echo out > /sys/class/gpio/gpio$CAM_REG_GPIO/direction
	echo 1 > /sys/class/gpio/gpio$CAM_REG_GPIO/value
fi

chroot ${QTIPATH} $@
