FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
DEPENDS += "libselinux-native"
SRC_URI += "file://0001-squashfs-tools-Allow-setting-selinux-xattrs-through-.patch;striplevel=2"
EXTRA_OEMAKE_append = "${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' WITH_SELINUX=1', '', d)}"
CFLAGS_append = "${@bb.utils.contains('DISTRO_FEATURES', 'selinux', ' -I${STAGING_INCDIR}/libselinux', '', d)}"
