diff -crB a/communication.c b/communication.c
*** a/communication.c	2012-12-25 00:04:43.686470000 +0530
--- b/communication.c	2012-12-25 00:04:39.066470000 +0530
***************
*** 282,288 ****
  	}
  close_file:
  	fclose(file);
! 	return 0;
  }
  
  /* Gets executed after ebt_deliver_table. Delivers the counters to the kernel
--- 282,288 ----
  	}
  close_file:
  	fclose(file);
! 	return ret;
  }
  
  /* Gets executed after ebt_deliver_table. Delivers the counters to the kernel
diff -crB a/Makefile b/Makefile
*** a/Makefile	2011-12-16 01:32:47.000000000 +0530
--- b/Makefile	2012-12-26 16:04:15.551120000 +0530
***************
*** 5,25 ****
  PROGVERSION_:=2.0.10
  PROGVERSION:=$(PROGVERSION_)-$(PROGRELEASE)
  PROGDATE:=December\ 2011
! LOCKFILE?=/var/lib/ebtables/lock
  LOCKDIR:=$(shell echo $(LOCKFILE) | sed 's/\(.*\)\/.*/\1/')/
  
  # default paths
! LIBDIR:=/usr/lib
! MANDIR:=/usr/local/man
! BINDIR:=/usr/local/sbin
! ETCDIR:=/etc
! INITDIR:=/etc/rc.d/init.d
! SYSCONFIGDIR:=/etc/sysconfig
  DESTDIR:=
  
  CFLAGS:=-Wall -Wunused -Werror
  CFLAGS_SH_LIB:=-fPIC -O3
! CC:=gcc
  
  ifeq ($(shell uname -m),sparc64)
  CFLAGS+=-DEBT_MIN_ALIGN=8 -DKERNEL_64_USERSPACE_32
--- 5,25 ----
  PROGVERSION_:=2.0.10
  PROGVERSION:=$(PROGVERSION_)-$(PROGRELEASE)
  PROGDATE:=December\ 2011
! LOCKFILE?=${localstatedir}lib/ebtables/lock
  LOCKDIR:=$(shell echo $(LOCKFILE) | sed 's/\(.*\)\/.*/\1/')/
  
  # default paths
! LIBDIR:=${libdir}
! MANDIR:=${mandir}
! BINDIR:=${sbindir}
! ETCDIR:=${sysconfdir}
! INITDIR:=${ETCDIR}/rc.d/init.d
! SYSCONFIGDIR:=${ETCDIR}/ebtables
  DESTDIR:=
  
  CFLAGS:=-Wall -Wunused -Werror
  CFLAGS_SH_LIB:=-fPIC -O3
! CC:=${CC}
  
  ifeq ($(shell uname -m),sparc64)
  CFLAGS+=-DEBT_MIN_ALIGN=8 -DKERNEL_64_USERSPACE_32
***************
*** 32,38 ****
  
  OBJECTS:=$(OBJECTS2) $(EXT_OBJS) $(EXT_LIBS)
  
! KERNEL_INCLUDES?=include/
  
  ETHERTYPESPATH?=$(ETCDIR)
  ETHERTYPESFILE:=$(ETHERTYPESPATH)/ethertypes
--- 32,38 ----
  
  OBJECTS:=$(OBJECTS2) $(EXT_OBJS) $(EXT_LIBS)
  
! KERNEL_INCLUDES?=${STAGING_KERNEL_DIR}/source/include
  
  ETHERTYPESPATH?=$(ETCDIR)
  ETHERTYPESFILE:=$(ETHERTYPESPATH)/ethertypes
***************
*** 90,97 ****
  	$(CC) -shared $(LDFLAGS) -Wl,-soname,libebtc.so -o libebtc.so -lc $(OBJECTS2)
  
  ebtables: $(OBJECTS) ebtables-standalone.o libebtc.so
! 	$(CC) $(CFLAGS) $(CFLAGS_SH_LIB) $(LDFLAGS) -o $@ ebtables-standalone.o -I$(KERNEL_INCLUDES) -L. -Lextensions -lebtc $(EXT_LIBSI) \
! 	-Wl,-rpath,$(LIBDIR)
  
  ebtablesu: ebtablesu.c
  	$(CC) $(CFLAGS) $(PROGSPECSD) $< -o $@
--- 90,96 ----
  	$(CC) -shared $(LDFLAGS) -Wl,-soname,libebtc.so -o libebtc.so -lc $(OBJECTS2)
  
  ebtables: $(OBJECTS) ebtables-standalone.o libebtc.so
! 	$(CC) $(CFLAGS) $(CFLAGS_SH_LIB) $(LDFLAGS) -o $@ ebtables-standalone.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
  
  ebtablesu: ebtablesu.c
  	$(CC) $(CFLAGS) $(PROGSPECSD) $< -o $@
***************
*** 100,114 ****
  	$(CC) $(CFLAGS) $(PROGSPECSD) -c $< -o $@  -I$(KERNEL_INCLUDES)
  
  ebtablesd: $(OBJECTS) ebtablesd.o libebtc.so
! 	$(CC) $(CFLAGS) -o $@ ebtablesd.o -I$(KERNEL_INCLUDES) -L. -Lextensions -lebtc $(EXT_LIBSI) \
! 	-Wl,-rpath,$(LIBDIR)
  
  ebtables-restore.o: ebtables-restore.c include/ebtables_u.h
  	$(CC) $(CFLAGS) $(PROGSPECS) -c $< -o $@  -I$(KERNEL_INCLUDES)
  
  ebtables-restore: $(OBJECTS) ebtables-restore.o libebtc.so
! 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ ebtables-restore.o -I$(KERNEL_INCLUDES) -L. -Lextensions -lebtc $(EXT_LIBSI) \
! 	-Wl,-rpath,$(LIBDIR)
  
  .PHONY: daemon
  daemon: ebtablesd ebtablesu
--- 99,111 ----
  	$(CC) $(CFLAGS) $(PROGSPECSD) -c $< -o $@  -I$(KERNEL_INCLUDES)
  
  ebtablesd: $(OBJECTS) ebtablesd.o libebtc.so
! 	$(CC) $(CFLAGS) -o $@ ebtablesd.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
  
  ebtables-restore.o: ebtables-restore.c include/ebtables_u.h
  	$(CC) $(CFLAGS) $(PROGSPECS) -c $< -o $@  -I$(KERNEL_INCLUDES)
  
  ebtables-restore: $(OBJECTS) ebtables-restore.o libebtc.so
! 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ ebtables-restore.o -I$(KERNEL_INCLUDES) -L. -Lextensions -Wl,--no-as-needed $(EXT_LIBSI) -lebtc
  
  .PHONY: daemon
  daemon: ebtablesd ebtablesu
