diff -crB a/Makefile b/Makefile
*** a/Makefile	2012-04-22 10:33:24.000000000 +0530
--- b/Makefile	2013-03-27 13:33:15.721149890 +0530
***************
*** 9,25 ****

  # Normal Makefile

- KERNELDIR := /lib/modules/`uname -r`/build
  all: 
! 	$(MAKE) -C $(KERNELDIR) M=`pwd` modules

  debug:
! 	$(MAKE) -C $(KERNELDIR) EXTRA_CFLAGS=-DDEBUG M=`pwd` modules

  modules_install:
! 	$(MAKE) -C $(KERNELDIR) M=`pwd` modules_install

  clean:
  	rm -rf *.o *.ko *.mod.c .*.cmd Module.symvers modules.order .tmp_versions

! endif
--- 9,24 ----

  # Normal Makefile

  all:
! 	$(MAKE) -C $(KSOURCE) M=$(CURDIR) modules

  debug:
! 	$(MAKE) -C $(KSOURCE) EXTRA_CFLAGS=-DDEBUG M=$(CURDIR) modules

  modules_install:
! 	$(MAKE) -C $(KSOURCE) M=$(CURDIR) modules_install

  clean:
	rm -rf *.o *.ko *.mod.c .*.cmd Module.symvers modules.order .tmp_versions

! endif
\ No newline at end of file
