#! /bin/sh

set -e

case "$1" in
  start)
    echo -n "Starting btproperty: "
    start-stop-daemon -S -b -a /usr/bin/btproperty
    echo "done"
    ;;
  stop)
    echo -n "Stopping btproperty: "
    start-stop-daemon -K -n btproperty
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage btproperty { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
